name: ROS2 (Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Based on example provided at https://github.com/ros-tooling/setup-ros

jobs:
  build_docker: # On Linux, use docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        ros_distribution:
          - humble
          - jazzy
          - rolling

        # Define the Docker image(s) associated with each ROS distribution.
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            ros_distribution: humble
            ros_version: 2

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
            ros_distribution: jazzy
            ros_version: 2

          # Rolling Ridley  (June 2020 - Present)
          - docker_image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
            ros_distribution: rolling
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-program-options-dev libusb-1.0-0-dev

      - name: install pip dependencies
          # TODO: would be better to follow https://answers.ros.org/question/370666/how-to-declare-an-external-python-dependency-in-ros2/
          # but this requires some upstream changes

          # colcon still does not seem to properly support venv, so we use a workaround to install
          # a python package globally by disabling the externally managed flag that is default on Ubuntu 24.04
        run: |
          sudo rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED
          pip install rowan

      - uses: actions/checkout@v2
      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            crazyflie
            crazyflie_examples
            crazyflie_interfaces
            crazyflie_py
            crazyflie_sim
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: rosinstall
